### ISSUE TITLE
Request for the latest release on PlatformIO

### ISSUE THREAD

**Issue by yuzukihironaka-lefixea** [alkonosst/SSLClient#11]
Hi @alkonosst ,

It semms like the latest version on PlatformIO is `v2.0.0`.

Colud you please publish the latest library?

Thank you.

**Comment by alkonosst** [comment]
Hi, it's done. Thank you for asking, I didn't know PlatformIO hadn't updated the registry automatically.

**Comment by yuzukihironaka-lefixea** [comment]
Thank you so much!
