### ISSUE TITLE
how to use setCACertBundle with the Arduino IDE for ESP32

### ISSUE THREAD

**Issue by kgmuzungu** [alkonosst/SSLClient#12]
**Is your feature request related to an issue? Please describe.**
I dont get how to declare/reference the x509_crt_bundle.bin file to compile in the Arduino IDE
// * Certificate bundle with 41 most used root certificates
extern const uint8_t ca_cert_bundle_start[] asm("_binary_data_crt_x509_crt_bundle_bin_start");
extern const uint8_t ca_cert_bundle_end[] asm("_binary_data_crt_x509_crt_bundle_bin_end");

**Describe the solution you would like**
Tiny tutorial/example code of how to include a cert bundle in the Arduino IDE

**Describe the alternatives you have considered**
No clue

**Additional context**
n/a

**Comment by alkonosst** [comment]
Hi, sorry there is no easy way to use a certificate bundle with Arduino IDE. Please read this topic on [arduino-esp32 on GitHub](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/README.md#using-a-bundle-of-root-certificate-authority-certificates).

You can use PlatformIO (I really advice you to use it) to test the example included in this library.

**Comment by kgmuzungu** [comment]
I will try PlatfromIO, looks great.
